# Generated by Django 4.2.15 on 2024-08-07 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitterAccount',
            new_name='UserData',
        ),
    ]
